import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { faker } from '@faker-js/faker'

// const content = (idx: number) => <div key={idx.toString()}><a href="https://twitter.com/gunnarmorling/status/1610203324963516417">@{faker.name.firstName().toLowerCase()}</a>&nbsp;wrote&nbsp;<blockquote className={styles.quoted}>{faker.lorem.paragraph(2).substring(0, 280)}</blockquote></div>

type Tweet = {
  link: string
  text: string
  author: string
}

type TweetsWithSummary = {
  summary: string
  tweets: Tweet[]
}

export async function getStaticProps(): Promise<{ props: { tweetsWithSummary: TweetsWithSummary }}> {
  return {
    props: {
      tweetsWithSummary: {
        summary: faker.lorem.paragraph(10),
        tweets: [...Array(100)].map(_ => ({
          text: faker.lorem.paragraph(2).substring(0, 280),
          link: "https://twitter.com/gunnarmorling/status/1610203324963516417",
          author: faker.name.firstName().toLowerCase(),
        })),
      },
    },
  }
}

export default function Home({ tweetsWithSummary }: { tweetsWithSummary: TweetsWithSummary}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.summary}>
          {tweetsWithSummary.summary}
        </div>
        <div>
          {tweetsWithSummary.tweets.map((t, idx) => <div key={idx.toString()}><a href={t.link}>@{t.author}</a>&nbsp;wrote&nbsp;<blockquote className={styles.quoted}>{t.text}</blockquote></div>)}
        </div>
      </main>
    </>
  )
}
